### Buscar todas as usuarios
GET http://localhost:3000/api/usuario

### Buscar usuario por ID
GET http://localhost:3000/api/usuario/8f99dd77-a35d-482e-b93e-87f981d4f77d

### Criar novo usuario
POST http://localhost:3000/api/usuario
Content-Type: application/json

{
  "nome": "Gabrielle",
  "email": "gabrielle@gmail.com",
  "senha": "123456"
}

### Atualizar usuario
PUT http://localhost:3000/api/usuario/5224309f-202d-4693-bb9a-29ad82145aae
Content-Type: application/json

{
  "nome": "Gabriele",
  "email": "gabriele@gmail.com",
  "senha": "123456"
}

### Deletar usuario
DELETE http://localhost:3000/api/usuario/1073946d-9a6c-42dc-8882-1f60f057370c


# Eventos --------------------------------------

### Buscar todas os eventos
GET http://localhost:3000/api/evento 

### Buscar evento por ID
GET http://localhost:3000/api/evento/2e6889ac-f3ce-4243-b75d-0489d3b7a5a7


### Criar novo evento
POST http://localhost:3000/api/evento
Content-Type: application/json

{
  "nome_evento": "Fashion Year",
  "data": "2025-05-25",
  "local": "Rio de Janeiro, Brasil",
  "descricao": "Desfile de moda no Rio"
}


### Atualizar evento
PUT http://localhost:3000/api/evento/2e6889ac-f3ce-4243-b75d-0489d3b7a5a7
Content-Type: application/json

{
  "nome_evento": "Fashion Week SP",
  "data": "2025-05-30",
  "local": "São Paulo, Brasil",
  "descricao": "Desfile de moda em São Paulo"
}

### Deletar evento
DELETE http://localhost:3000/api/evento/002ff5f0-a0ad-40b6-95d1-20a2ed56ab07

# Inscrições --------------------------------------

### Buscar todas as inscrições
GET http://localhost:3000/api/inscricao 

### Buscar inscrição por ID
GET http://localhost:3000/api/inscricao/24142e39-e9f8-4eda-9626-d99cdb4df100


### Criar nova inscrição
POST http://localhost:3000/api/inscricao
Content-Type: application/json
  
{
  "data": "2025-05-27",
  "status": "Agendado",
  "id_usuario": "8f99dd77-a35d-482e-b93e-87f981d4f77d",
  "id_evento": "2e6889ac-f3ce-4243-b75d-0489d3b7a5a7"
}


### Atualizar inscrição
PUT http://localhost:3000/api/inscricao/24142e39-e9f8-4eda-9626-d99cdb4df100
Content-Type: application/json

{
  "data": "2025-05-26",
  "status": "Confirmado",
  "id_usuario": "8f99dd77-a35d-482e-b93e-87f981d4f77d",
  "id_evento": "2e6889ac-f3ce-4243-b75d-0489d3b7a5a7"
}

### Deletar inscrição
DELETE http://localhost:3000/api/inscricao/24142e39-e9f8-4eda-9626-d99cdb4df100
